### ISSUE TITLE
Main thread performance issues

### ISSUE THREAD

**Issue by tjhancocks** [Tealium/ios-library#13]
I'm currently experiencing some issues regarding performance with Tealium when tracking events when lots of user interaction is occurring (for example scrolling a Collection View).

The method in particular taking up a lot of time on the main thread is:

    -[TealiumCommHandler dispatchActual:clearSent:completionBlock:]_block_invoke
        +[TealiumInternalConstants performBlockOnMainThread:]_block_invoke

Is there a way to tell the library to use a background thread when dispatching events?

**Comment by patrickmcwilliams** [comment]
@tjhancocks ,
Could you tell us what version of the library you are using? If you are not on the most current, can you try the most current version and see if what you are experiencing persists? 4.1 introduced a new threading model that may help with what you are seeing. Also, there is a class exclusion that can be used to exclude certain classes that end up causing the library to spam itself with excessive calls that are unneeded. https://github.com/Tealium/ios-library/wiki/Advanced-Guide#exclude-classes-from-tracking

**Comment by tjhancocks** [comment]
We're currently using 4.0.6c, but I will upgrade the library to 4.1c.

**Comment by patrickmcwilliams** [comment]
@tjhancocks .. awesome, let us know how that goes for you. Remember there is the class exclusion as well if you need to tweak the behavior further as well. If you know there are classes that you will never track that are being tracked, you can exclude them. That also work for subclassing to allow you to mark some objects that are technically the same type of object but exclude a subset by excluding the subclass.
just an fyi
