### ISSUE TITLE
Debug log

### ISSUE THREAD

**Issue by manismku** [Tealium/ios-library#15]
Wanted to see DebugLog in xCode so that I can verify custom Data sent. All I see is 
Queued manual view dispatch for ViewData : appeared :
but not actual data sent. 
Any idea where I check it ?

**Comment by ethyreal** [comment]
You can use the verbose logging option ```TLDisplayVerboseLogs```:

```objective-c
    [Tealium initSharedInstance:@"tealiummobile"
                        profile:@"demo"
                         target:@"dev"
                        options:TLDisplayVerboseLogs];

```

That will give you a dump of all the data queued for dispatch.

If you want to see what actually fires to each tag vendor I would recommend using a proxy like [Charles](http://www.charlesproxy.com).

**Comment by patrickmcwilliams** [comment]
@manismku .. we have a feature called liveEvents and trace in tealiumIQ, these will allow you to see the data sent on each request. 
- We have to add a dataCloud tag to your profile to enable liveEvents and trace. (suggested route, contact your account manager for help with this)
- You also have the option of using a proxy like Charles and adding a dummy pixel using the tealium EventStream tag and monitoring for that pixel in Charles. This pixel will have all of your data as querystrings.
- The last option would be using a 3rd party http request inspector service and putting in the URL to their endpoint in the EventStream config. You could then see the data through that service.

**Comment by manismku** [comment]
@ethyreal @patrickmcwilliams Thanks for quick response. Now, I am able to do see data dump.
