### ISSUE TITLE
iOS Tealium crash - unable to disable autotrack

### ISSUE THREAD

**Issue by manismku** [Tealium/ios-library#18]
Hi,

I am trying to disable auto track  for view through following call but it seems it is not allowing disable.
Objective is to selectively disable the autotrack from a particular view. I don't want to use exclude class from plist since I wanted to selectively disable autotrack event.
-(void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    NSDictionary *temp = @{TealiumDSK_Autotracked:@"false"};
    [Tealium addCustomData:temp toObject:self.view];
}

Reason to do above is following crash which results due to autodispatch of the event.

bool _WebTryThreadLock(bool), 0x7fd01e292900: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...
1   0x10c128f5b WebThreadLock
2   0x104aa74c9 -[UIWebDocumentView text]
3   0x1048e1952 -[UIView(UIDebugging) description]
4   0x1065982cf _NSDescriptionWithLocaleFunc
5   0x10702e86d __CFStringAppendFormatCore
6   0x107113c10 _CFStringCreateWithFormatAndArgumentsAux2
7   0x106598248 -[NSPlaceholderString initWithFormat:locale:arguments:]
8   0x10659b7e8 +[NSString stringWithFormat:]
9   0x103eda081 -[TealiumActual dispatchActual:customData:callType:wasAutotracked:priority:completionBlock:]
10  0x103ed656e +[TealiumActual trackCallType:customData:object:autotracked:completionBlock:]
11  0x103eda6de +[TealiumActual autotrackEvent:]
12  0x103edcd25 __TealiumSendEvent_block_invoke63
13  0x107bdacc6 _dispatch_call_block_and_release
14  0x107bf87f4 _dispatch_client_callout
15  0x107be0bf4 _dispatch_queue_drain
16  0x107be0506 _dispatch_queue_invoke
17  0x107be2ff7 _dispatch_root_queue_drain
18  0x107be463c _dispatch_worker_thread2
19  0x107f8eef8 _pthread_wqthread
20  0x107f91fb9 start_wqthread

**Comment by ethyreal** [comment]
Hi,

There is a bug in the auto tracking logging of WebView objects.  I have submitted a fix for our next release.  In the meantime if you are working with WebViews I would recommend not using the ```TLDisplayVerboseLogs``` launch option as the debug logging is where this crash is.

In your application delegate use the ```TLSuppressLogs``` launch option like this:
```objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    // your setup code..
    [Tealium initSharedInstance:@"tealiummobile"
                        profile:@"demo"
                         target:@"dev"
                        options:TLSuppressLogs
               globalCustomData:nil];

    return YES;
}
```

Internally suppressing logs prevents this bug from appearing in the 4.1.2 version of the library.  If this does not fix the issue for you please let me know.

**Comment by manismku** [comment]
@ethyreal  This indeed solved our issue. :)
Great and thank you for quick response.

**Comment by ethyreal** [comment]
You're welcome.
