### ISSUE TITLE
how to disable Duplicate call from <ViewController: 0x7fd20606f000> suppressed.

### ISSUE THREAD

**Issue by charlyliu** [Tealium/ios-library#21]
I'm using AOPAspect to intercept method calls. I have 2 events that is triggered at the same time. 1 event is an TealiumEventCall and the other is TealiumViewCall. I want to send both events but the output tells me that one call is suppressed.

2015-04-02 17:17:05.989 MyApp[34375:1735931] TEALIUM 4.1.2c: Packaged Dispatch Data Sources: (
...............
)
2015-04-02 17:17:05.994 MyApp[34375:1735931] TEALIUM 4.1.2c: All dispatches sent.
2015-04-02 17:17:05.994 MyApp[34375:1735931] TEALIUM 4.1.2c: Duplicate call from <ViewController: 0x7fe8dfe1a000> suppressed.

The 2 events are not the same either, the custom data are very different. The only thing that is the same is that is from the same ViewController.

Do you know how can I disable this duplicated behaviour?

**Comment by ethyreal** [comment]
Unfortunately there is a bug in our current duplicate suppression.  It is fixed for the next release but until that ships I have a couple possible solutions I gave in detail here:

https://github.com/Tealium/ios-library/issues/16#issuecomment-76219844

I hope one of those approaches works for you until we release our update.

**Comment by charlyliu** [comment]
Thx ethyreal, Any Estimated Release Date for the next release?

We will try the workarounds and post here the results.

**Comment by ethyreal** [comment]
@charlyliu Sorry for the late response.  We plan to release a patch by end the of the day today.

**Comment by charlyliu** [comment]
Thank you
