### ISSUE TITLE
-customDataForObject Not working properly

### ISSUE THREAD

**Issue by eriksundin** [Tealium/ios-library#23]
In Tealium 4.1.4 the method -customDataForObject: stopped working properly.
Where we in 4.1.2 got a dictionary back with proper custom data, we now get nil.

Kind Regards,
Erik

**Comment by jalakoo** [comment]
Hi Erik,

Just double checking that you're getting nil returned, and not an empty dictionary?  We just retested in several simulators and two devices (iPadMini and iPhone 5 both running 8.1.3)  and we're seeing custom data return as expected.

We're presuming you've used the "addCustomData:toObject:"  method on the same object prior to "customDataForObject:" call.  If you could paste copies of the exact code snippets you're using and provide details on the target object, that may help us find the issue.

**Comment by eriksundin** [comment]
Hi,

I've setup a test project for you, download it here: https://www.dropbox.com/s/mdehov82e7cu4h8/TealiumBug.zip?dl=0

Just clone the Tealium git lib into the root folder and the Xcode project will link in the Compact version by relative path.

It's a simple app with two buttons, one which will set custom data and one that will output it from the same object.
Try first by checking out the 4.1.2 tag of the lib. Output is as expected.
With the 4.1.4 tag the output will be null.

Regards,
Erik

**Comment by jalakoo** [comment]
Oh, the Compact version 4.1.4c does not execute the addCustomData:toObject: or customDataForObject: commands as these are only needed by the full library, for adding data to auto tracked objects.  If using the compact, use the trackCallType:customData:object: command with the custom data at time of call.

We'll be updating our documentation to clarify this as it's not currently documented.

**Comment by eriksundin** [comment]
Wow, Ok. That's a pretty breaking change if one's tracking infrastructure is build upon decorating, for instance, your view controllers with context information that is used when submitting tracking calls. (Yes, ours is.)

Consider a View Controller A having knowledge about context that a view controller B does not have.
Controller A can decorate B before presenting it with proper context and, for instance, a page view in controller B with 'self' as object will provide the complete context wanted including any extra parameters passed as in -trackCallType:customData:object:

That is a simple example but I would say there is definitely a use for the API for end-users even though it might not be needed internally in the compact library.

Unless you have other reasons for closing this functionality, would you consider to make it available to users of the compact library again?

Kind Regards,
Erik

**Comment by jalakoo** [comment]
Hey Erik,

Excellent points, so yes, we will happily re-enable that function for the Compact in our next version release, 4.1.5.  

I should be able to get this out for you by end of day this Friday.

**Comment by eriksundin** [comment]
Much appreciated @jalakoo ! Looking forward to the 4.1.5 release.
