### ISSUE TITLE
Tealium.h missing @interface declaration in Compact?

### ISSUE THREAD

**Issue by jeffalgera** [Tealium/ios-library#25]
Compact library -> TealiumLibrary.framework/Headers/Tealium.h should have 
````
@interface Tealium : NSObject 
````
After the import declarations.  I don't see it in the latest downloaded.

**Comment by ethyreal** [comment]
I'm not sure where you are looking.

However the Tealium.h file is symlinked in frameworks.  The actual file is here:

https://github.com/Tealium/ios-library/blob/master/TealiumCompact/TealiumLibrary.framework/Versions/A/Headers/Tealium.h

I see the import statement on my end.  Please let me know if this is still problem for you.

**Comment by ethyreal** [comment]
I've just downloaded the zip of the repo and followed the links downloaded.  I see the full contents of the file there as well.

**Comment by jeffalgera** [comment]
Me too, also saw the import this time around.  Thanks for checking it out.
