### ISSUE TITLE
duplicate symbol _kReachabilityChangedNotification error

### ISSUE THREAD

**Issue by waymanng** [Tealium/ios-library#26]
Another library we're linking contains this property and we're getting a duplicate symbol error.  Is there a fix for this?  

Thanks!

**Comment by jalakoo** [comment]
Yes, we will be releasing an update before the end of the week.  

Alternatively, if you have access to the reachability.h and .m files of the other library, you could change the *kReachabilityChangedNotification* constant to something different, like *kTMReachabilityChangedNotification*, this will likely be required in 3 places within that library.

**Comment by ethyreal** [comment]
@waymanng We have updated our library correcting this conflict on our end.  You can pull down the latest ( 4.1.8 ) from git or download directly here:

https://github.com/Tealium/ios-library/releases/tag/4.1.8

Kind regards

**Comment by waymanng** [comment]
@jalakoo @ethyreal : The new version compiles and links fine now.  Thanks!
