### ISSUE TITLE
No ARM64 build available

### ISSUE THREAD

**Issue by ThomasAnnerel** [Tealium/ios-library#27]
For new submit to the IOS store we need a armV64 build urgently

**Comment by ethyreal** [comment]
@ThomasAnnerel  We ship a fat binary that includes arm64 among others.  To my knowledge armV64 is not a architecture of any iOS device. 

If you browse into our .framework file until you get to the underlying .a static library you can run ```lipo``` and see for yourself:

```
Georges-MacBook-Pro:Current ethyreal$ lipo TealiumLibrary -info
Architectures in the fat file: TealiumLibrary are: i386 armv7 armv7s x86_64 arm64 
```
