### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by FGoessler** [Tealium/ios-library#30]
Since [Cocoapods](https://cocoapods.org) is the most common dependency management tool for iOS it would be great if this framework could be accessible through that channel as well, cause it significantly simplifies the installation and update process.

The documentation about how to create a pod can be found here: https://guides.cocoapods.org/making/index.html

For question and help feel free to contact me.

**Comment by FloresRobles** [comment]
+1

**Comment by jalakoo** [comment]
Thanks for the input. Cocoapods support is planned to be available with the next version update of the libraries.

**Comment by msson** [comment]
Any update on when the next version will be released?

**Comment by jalakoo** [comment]
We are planning on having the next version available before the end of this year.

**Comment by garethknowles** [comment]
The end of the year is approaching, any further updates on the next version?

**Comment by jalakoo** [comment]
Hey @garethknowles, we've decided to put in a little extra time to add support for additional devices, currently looking good for release within January.

**Comment by svachmic** [comment]
+1 (January of which year? :))

**Comment by jalakoo** [comment]
Thank you for your patience everyone, version 5.x is now available for iOS and tvOS at: 

https://github.com/tealium/tealium-ios
https://github.com/tealium/tealium-tvos

pods for each are:

pod 'TealiumIOS'
pod 'TealiumTVOS'

**Comment by svachmic** [comment]
Hey guys, unfortunately I am getting [!] Unable to find a specification for `TealiumIOS` - I couldn't find the podspec in the repo, perhaps it's because of that...

**Comment by jalakoo** [comment]
Our understanding was that the podspec wasn't necessary in our repo since it's in [Cocoapods spec repo](https://github.com/CocoaPods/Specs/blob/master/Specs/TealiumIOS/5.0.0/TealiumIOS.podspec.json).

Could you paste a copy of your podfile here for us to troubleshoot with?

**Comment by svachmic** [comment]
Sure, here it is:

> platform :ios, '8.0'
> use_frameworks!
>
> pod 'Alamofire', '~> 3.0'
> pod 'TealiumIOS'

**Comment by jalakoo** [comment]
Ah, the minimum iOS target version supported for 5.x framework is 8.1
