### ISSUE TITLE
Crash on iPad, iOS7

### ISSUE THREAD

**Issue by eriksundin** [Tealium/ios-library#31]
We're noticing a re-occuring crash in our app on (almost exclusively) iPads running iOS7.
The app is using the 4.1.6c version of the library.

From Crashlytics:

```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0xb1898840

Thread : Crashed: com.tealium.shared-thread
0  libobjc.A.dylib                0x393210ec objc_retain + 11
1  libobjc.A.dylib                0x3932f617 objc_storeStrong + 22
2  blocket                        0x0048e8dd +[TealiumActual trackCallType:customData:object:autotracked:completionBlock:] (TealiumActual.m:166)
3  blocket                        0x004737f3 __43+[Tealium trackCallType:customData:object:]_block_invoke (Tealium.m:52)
4  libdispatch.dylib              0x39807d1b _dispatch_call_block_and_release + 10
5  libdispatch.dylib              0x3980e273 _dispatch_queue_drain$VARIANT$mp + 374
6  libdispatch.dylib              0x3980e06b _dispatch_queue_invoke$VARIANT$mp + 42
7  libdispatch.dylib              0x3980ece1 _dispatch_root_queue_drain + 76
8  libdispatch.dylib              0x3980ef59 _dispatch_worker_thread2 + 56
9  libsystem_pthread.dylib        0x39949dbf _pthread_wqthread + 298
10 libsystem_pthread.dylib        0x39949c84 start_wqthread + 8
```

Are you familiar with this crash? Maybe it is fixed in the latest version already?

Best Regards,
Erik

**Comment by jalakoo** [comment]
Hi Erik,

I'm presuming this crash reported is from iPads running your app in the wild, are you also seeing this on an iPad running iOS7 in development?

**Comment by eriksundin** [comment]
Yes, exactly @jalakoo, we've picked this crash up from the wild through Crashlytics. It has not been reproduced in development.

**Comment by jalakoo** [comment]
@eriksundin We have not seen this particular crash before but from the crash log provided I believe our library may be attempting to hold onto an object that was already deallocated.  I can't say if the incremental version releases after 4.1.6c would solve this, but the 5.0 version in development is architected in a way that would not allow this.

Where there any devices you have access to that crashed that additional logs could be extracted from?  https://developer.apple.com/library/ios/qa/qa1747/_index.html

**Comment by eriksundin** [comment]
Unfortunately we don't have any additional logs at the moment. If we come across it I will supply it here.
For the time being, this is minor issue, at least for us. It has happened to a quite small group of our users.
I was just hoping you might have come across it already.

I will let you know how it progresses and looking forward to trying out the 5.0 version.

**Comment by jalakoo** [comment]
@eriksundin Version 5.x is now available at:

https://github.com/tealium/tealium-ios
https://github.com/tealium/tealium-tvos

Version 5.x makes a copy of all data needed on the main thread then is sent to a background thread for dispatching which should prevent the error you encountered from occurring.
