### ISSUE TITLE
Disable UI auto-tracking

### ISSUE THREAD

**Issue by felipeparpinelli** [Tealium/ios-library#32]
Is it possible to disable an UI auto-tracking dispatch for a view? Even using the full version? We're tagging manually. 

Thanks

**Comment by jalakoo** [comment]
Since you're manually tagging you can disable all autotracking through your TIQ Dashboard:

1. Click on the "Save/Publish" button
2. Click on the "Configure Publish Settings..." button
3. Mobile Library Publishing Tab
4. Turn OFF the "UI Auto Tracking" option
5. Save & Re-publish

**Comment by felipeparpinelli** [comment]
Thank you very much!
Felipe.
