### ISSUE TITLE
Crash iOS

### ISSUE THREAD

**Issue by felipeparpinelli** [Tealium/ios-library#33]
Hi,

We're noticing a occuring crash in our app:

Fatal Exception: NSGenericException
*** Collection <__NSDictionaryM: 0x16522800> was mutated while being enumerated.

Thread : Fatal Exception: NSGenericException
0  CoreFoundation                 0x23c2c67b __exceptionPreprocess
1  libobjc.A.dylib                0x357dae17 objc_exception_throw
2  CoreFoundation                 0x23c2c101 -[NSException name]
3  CoreFoundation                 0x23b50bfb -[NSMutableDictionary addEntriesFromDictionary:]
4  Our App                     0x1c6cd7 -[TealiumActual dispatchActual:customData:callType:wasAutotracked:priority:completionBlock:] (TealiumActual.m:637)
5  Our App                     0x1c3dd3 +[TealiumActual trackCallType:customData:object:autotracked:completionBlock:] (TealiumActual.m:247)
6  Our App                     0x1c7103 +[TealiumActual autotrackEvent:] (TealiumActual.m:677)
7  Our App                     0x1c8afd __TealiumSendEvent_block_invoke61 (UIApplication+TealiumTracker.m:70)
8  libdispatch.dylib              0x35effbeb _dispatch_call_block_and_release
9  libdispatch.dylib              0x35f0c7eb _dispatch_queue_drain$VARIANT$mp
10 libdispatch.dylib              0x35f0be29 _dispatch_queue_invoke$VARIANT$mp
11 libdispatch.dylib              0x35f0e9b1 _dispatch_root_queue_drain
12 libdispatch.dylib              0x35f0e395 _dispatch_worker_thread3
13 libsystem_pthread.dylib        0x360b9b29 _pthread_wqthread
14 libsystem_pthread.dylib        0x360b9718 start_wqthread

Can you help us?

Thanks, 
Felipe

**Comment by ChadHartman** [comment]
Alrighty, just need some info: 
* What version of the library are you using? 
* What os versions are you seeing the crash on?
* What devices are you seeing the crash on?

**Comment by felipeparpinelli** [comment]
1. TealiumLibraryVersion: 4.1.11
2. 70% iOS 9 and 30% iOS 8
3. 77% iPhone, 22% iPad and 1% iPod

Thanks,
Felipe

**Comment by jalakoo** [comment]
Hey Felipe,

Are you using a crash tracking service, such as Crashlytics?  If so, we recommend disabling our library's crash tracking. In the init method, options argument, add the "TLDisableExceptionHandling" flag (https://github.com/Tealium/ios-library/wiki/API-4.x#init-options)

**Comment by felipeparpinelli** [comment]
Hi Jalakoo,

I add the flag "TLDisableExceptionHandling" and it doesn't work. When i set [Tealium disable], all works fine.
The problem is something to do with some controls that we use (like play, pause, seek to) and the Tealium auto tracking. We do not need Tealium auto tracking, is there any way to disable it in code? Or only in Tealium IQ dashboard?

**Comment by jalakoo** [comment]
If using 4.1.11 UIAutotracking can only be disabled via the dashboard.  

Unfortunately, this only disables the sending of autotracked calls, not the underlying process. If the autotracking and mobile companion features are not being used, we recommend switching to version 4.1.11c (https://github.com/Tealium/ios-library/tree/master/TealiumCompact), which has not autotracking components in it.

**Comment by felipeparpinelli** [comment]
I do not know if we use the mobile companion,, How can we be sure? is something made in code or in the panel? What is the advantage of using? Thank you for your help.

**Comment by jalakoo** [comment]
Mobile Companion is primarily a post-deployment feature for your account manager to inspect/debug library elements without a dev environment (https://github.com/Tealium/ios-library/wiki/Advanced-Guide#mobile-companion-full-only).   

I would ask whoever is on your team who will be primarily using the Tealium dashboard as to whether or not they plan on using this feature.
