### ISSUE TITLE
Queueing issue

### ISSUE THREAD

**Issue by patrickmcwilliams** [Tealium/ios-library#35]
In using a sample app and 4.1.11c we noticed all calls being queued and occasionally being released. After trying all versions back to 4.1.1c and finally 4.1c, 4.1c is the latest version that not queue for no reason.

**Comment by patrickmcwilliams** [comment]
after loading the telium demo profile with 4.1.11 this issue doesnt seem to occur
this may be related to the new MPS? 
profile having issue is 
frb/consumeronlineios/dev

**Comment by jalakoo** [comment]
@patrickmcwilliams Indeed, that account-profile mobile.html only has MPS data for version 5., so the version 4 library in use will find no settings data and will auto-default to queueing. Fix: add the version 4 mobile publish settings and re-publish.
