### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by KITSTABLucianoMarisi** [Tealium/ios-library#37]
Would it be possible to have Bitcode support on the framework?

**Comment by jalakoo** [comment]
Hi @KITSTABLucianoMarisi,

Unfortunately, no additional fixes or features are planned for this version.  Please see our newer ObjC library at https://github.com/tealium/tealium-ios  or our new Swift library at https://github.com/tealium/tealium-swift.

**Comment by KITSTABLucianoMarisi** [comment]
Migrated this issue to the tealium-swift repository, https://github.com/Tealium/tealium-swift/issues/17
