### ISSUE TITLE
Tealium Crash iOS 11 enableRemoteCommands

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [Tealium/ios-library#39]
HI there,
We are using the Tealium Library as a pod with version 5.3. Now in production we have a lot of crashes in the function enableRemoteCommands. I attached a screenshot of the callstack. Has anybody the same problems. We do not use this method in our code. It seems that the release of that object crashed. 
![tealium](https://user-images.githubusercontent.com/35596604/35145590-a8944840-fd08-11e7-984e-0b9976a01819.jpeg)

**Comment by craigrouse** [comment]
@andreas-sommer-engenious this is the wrong git repo. This is the one you're looking for: https://github.com/Tealium/tealium-ios

Can you please re-post (and let me know exactly which version number; 5.3.1 is the latest, which contains a lot of bug fixes).
